SERVICE:
    SERVICE_IP: "0.0.0.0"
    TRACKING_PORT: 5004
    SERVICE_PORT: 5050
    CAR_RECOG_PORT: 5002
    COLOR_PORT: 5001
    DETECTION_PORT: 5003
    LOG_PATH: "logfile"
    BACKUP_DIR: "backup"
    STORE_FRAME: "store_frame"

    COLOR_LABELS: ["black", "blue", "brown", "green", "pink", "red", "silver", "white", "yellow"]
    COLOR_MODEL: "models/color_model.h5"

    CAR_RECOG_JSON: "models/MobileNets_car_recognition.json"
    CAR_RECOG_WEIGHTS: "models/car_recognition_weights.h5"
    CAR_RECOG_LABELS: "models/car_recognition_labels.txt"

    DETECT_WEIGHT: "models/detector.pth"
    DETECT_CONFIG: "detectron2/configs/COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml"
    THRESHOLD: 0.5
    NUMBER_CLASS: 5
    VEHICLE_CLASS: "models/vehicle_classes.txt" 
    DEVICE: 'cpu'

    DETECT_URL: 'http://192.168.28.75:5003/predict'
    COLOR_URL: 'http://192.168.28.75:5001/predict'
    CAR_RECOG_URL: 'http://192.168.28.75:5002/predict'

    # DETECT_URL: 'http://0.0.0.0:5003/predict'
    # COLOR_URL: 'http://0.0.0.0:5001/predict'
    # CAR_RECOG_URL: 'http://0.0.0.0:5002/predict'
    # SERVICE_URL: 'http://0.0.0.0:5050/predict'