SERVICE:
    SERVICE_IP: "0.0.0.0"
    COLOR_PORT: 5001
    CAR_RECOG_PORT: 5002
    LOG_PATH: "logfile"
    BACKUP_DIR: "backup"

    COLOR_LABELS: ["white", "green", "gray", "red", "blue", "black", "brown", "yellow"]
    COLOR_MODEL: "models/color_model.h5"

    CAR_RECOG_JSON: "models/EfficientNetB0_200epoch.json"
    CAR_RECOG_WEIGHTS: "models/EfficientNetB0_200epoch.h5"
    CAR_RECOG_LABELS: "models/car_recognition_labels.txt"

    DETECT_WEIGHT: "models/detector.pth"
    DETECT_CONFIG: "detectron2/configs/COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml"
    THRESHOLD: 0.5
    NUMBER_CLASS: 5
    VEHICLE_CLASS: "models/vehicle_classes.txt" 
    DEVICE: 'cpu'

    DETECT_URL: 'http://0.0.0.0:5003/predict'
    COLOR_URL: 'http://0.0.0.0:5001/predict'
    CAR_RECOG_URL: 'http://0.0.0.0:5002/predict'
    SERVICE_URL: 'http://0.0.0.0:5050/predict'
